<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <AdditionalFiles Include="Components\App.razor" />
      <AdditionalFiles Include="Components\Layout\MainLayout.razor" />
      <AdditionalFiles Include="Components\Pages\Chat.razor" />
      <AdditionalFiles Include="Components\Pages\Error.razor" />
      <AdditionalFiles Include="Components\Pages\Home.razor" />
      <AdditionalFiles Include="Components\Pages\Login.razor" />
      <AdditionalFiles Include="Components\Pages\Logout.razor" />
      <AdditionalFiles Include="Components\Pages\Manage\Account.razor" />
      <AdditionalFiles Include="Components\Routes.razor" />
      <AdditionalFiles Include="Components\_Imports.razor" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Extensions\" />
      <Folder Include="wwwroot\js\" />
      <Folder Include="wwwroot\lib\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
      <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.8" />
      <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.8" />
      <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.8" />
      <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.8" />
      <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.8" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.8" />
      <PackageReference Include="Microsoft.Net.Http.Headers" Version="9.0.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="CSharpFunctionalExtensions">
        <HintPath>..\..\..\.nuget\packages\csharpfunctionalextensions\3.6.0\lib\net8.0\CSharpFunctionalExtensions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
