<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>7f325a90-247c-426a-923a-ef49575f0754</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
        <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNet.SignalR.Client">
        <HintPath>..\..\..\.nuget\packages\microsoft.aspnet.signalr.client\2.0.3\lib\net45\Microsoft.AspNet.SignalR.Client.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.SignalR.Client.Core">
        <HintPath>..\..\..\.nuget\packages\microsoft.aspnetcore.signalr.client.core\9.0.8\lib\net9.0\Microsoft.AspNetCore.SignalR.Client.Core.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
